export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_FORUM = "SET_CURRENT_FORUM";
export const STORE_FORUM_POSTS = "STORE_FORUM_POSTS";
export const ADD_FORUM_POST = "ADD_FORUM_POST";